language: java
sudo: false

jdk:
  - oraclejdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

stages:
  - name: build
  - name: mutation-test
  - name: sonar-cloud

jobs:
  include:
    - stage: build
      script: ./gradlew clean build

deploy:
  provider: heroku
  app: sessao-votacao
  api_key:
    secure: $HEROKU_API_KEY


notifications:
  email:
    - guastalli31@gmail.com