language: java
sudo: false
install: true
jdk:
- oraclejdk11
before_script:
- chmod +x gradlew
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
stages:
- name: build
- name: sonar-cloud
- name: deploy
jobs:
  include:
  - stage: build
    script: "./gradlew clean build"
  - stage: sonar-cloud
    script: "./gradlew sonarqube -Dsonar.projectKey=RonaldoGuastalli_sessao-votacao
      -Dsonar.organization=ronaldoguastalli -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=c90bd40b900275ec8e6587e86d3f84d128e0d0af"
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      app: sessao-votacao
      api_key:
        secure: vstInhAHm8mSswenD8ePuG4wDmxrkCO6uEOTOw2zhKFhVqpyiW6DYNW/Pbg5aPtyNYNHtaztgfxGXsDdlM2eEZBFBBZ16ePVzasMIKGpY6g1MpfXH7TrOxLr7d7nE+W7NouJKFGZzIbo6toxtN/twxD86X8V2kTMcauq3hEPtflWuWcXwOmBPyvjdO/bjrH4eDw5WNY5kxGr3g8WTfQP3m7at/UUEJRLsJm3WCfm4lOglA8pyCn/OiJjOoEqhjqUfyICVcXE66NHpjWmptJ7flLiJ0/M9BuaE3K3ZdpMdDE3/2SuYqPyyNTw6etRQlp8XaxCUW0tq8WtsA/YhAa9+DBvgsEZvl2roW6xLuoWKge8rVnrsKZWlVoyMSU/DZHQDWJbZGzwN8m6AVyudI/XmZ1oThhMv1UkXiVHVw2OhjZG7TxYXJhtwo61TY4wqblyBba/dXh3AHgGzL9ykLC9CDqqkM/naBCYv2/YxvzlEaYmPZL6ZvovkRx7g2RJzX78AEbZAYylEETA0X2Sa5NB9P59dXcLDZ0+cklFF2nRvsY8IjnNBBRPac9ccra1yBqSRiZPgGz8xjLpXqz/5vSHZFidTORPd6YVpBdK0yXvacw6cH1WUH0LOEWbGD+63TQqHEAuYIATZ+ErA29SG3RiYw1lBifbLcZQliN88wDgkO4=

notifications:
  email:
  - guastalli31@gmail.com