# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: sessao-votacao
      MYSQL_ROOT_PASSWORD: admin
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
#    volumes:
#      - ./.docker/dbdata/:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

