CREATE TABLE IF NOT EXISTS SESSAO (
    ID SERIAL PRIMARY KEY,
    PAUTA_ID INTEGER REFERENCES PAUTA(ID),
    DATA_ABERTURA TIMESTAMP NOT NULL,
    DATA_TERMINO TIMESTAMP NOT NULL,
    SITUACAO INTEGER NOT NULL,
    TEMPO_ABERTURA INTEGER NOT NULL
);