CREATE TABLE IF NOT EXISTS VOTO_ASSOCIADO
(
    ID            SERIAL PRIMARY KEY,
    ID_SESSAO     INTEGER REFERENCES SESSAO(ID),
    CPF_ASSOCIADO VARCHAR(15) NOT NULL,
    VOTO          INTEGER     NOT NULL
);